server:
  port: 9896

spring:
  profiles:
    active: dev

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.waken.dorm.common.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

#自定义连接阿里云配置
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI9PTkJOaCmQK3
    accessKeySecret: v4LGdMC1KCTtELTkrQ3gDf9nTkHYMG
    bucketName: dorm-files
    fileHost: dorm-img
    accessUrl: https://dorm-files.oss-cn-shanghai.aliyuncs.com

#监控
management:
  endpoints:
    web:
      exposure:
# 暴露所有端点监控
        include: '*'


#dorm自定义属性配置
dorm:
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  properties:
    # 后端免认证接口 url
    anonUrl: /waken/dorm/login,/waken/dorm/logout/**,/waken/dorm/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 3600
